<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title"><?php echo $this->escapeHtml($this->titulo) ?></h4>
</div>
<form class="form-horizontal">
    <fieldset>
        <div class="modal-body">
            <div class="form-group">
                <label for="inputNombre" class="col-sm-2 control-label">Nombre</label>
                <div class="col-sm-10">
                    <input type="nombre" class="form-control" id="inputNombre" placeholder="Nombre" value="<?php echo $this->empleado->getName() ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="inputEmail" placeholder="Email" value="<?php echo $this->empleado->getEmail() ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="inputTelefono" class="col-sm-2 control-label">Telefono</label>
                <div class="col-sm-10">
                    <input type="telefono" class="form-control" id="inputTelefono" placeholder="Telefono" value="<?php echo $this->empleado->getPhone() ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="inputDireccion" class="col-sm-2 control-label">Dirección</label>
                <div class="col-sm-10">
                    <input type="direccion" class="form-control" id="inputDireccion" placeholder="Dirección" value="<?php echo $this->empleado->getAddress() ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPosicion" class="col-sm-2 control-label">Posición</label>
                <div class="col-sm-10">
                    <input type="posicion" class="form-control" id="inputPosicion" placeholder="Posicion" value="<?php echo $this->empleado->getPosition() ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="inputSalario" class="col-sm-2 control-label">Salario</label>
                <div class="col-sm-10">
                    <input type="salario" class="form-control" id="inputSalario" placeholder="Salario" value="<?php echo $this->empleado->getSalary() ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="inputHabilidades" class="col-sm-2 control-label">Habilidades</label>
                <div class="col-sm-10">
                    <select multiple class="form-control" id="inputHabilidades">
                    <?php foreach ($this->empleado->getSkills() as $key => $habilidad) : ?>
                        <option><?php echo trim($habilidad->getDescripcion())."\n" ?></option>
                    <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </fieldset>
</form>