<!-- begin page-header -->
<h1 class="page-header"><?php echo $this->escapeHtml($this->titulo) ?></h1>
<!-- end page-header -->

<!-- begin row -->
<div class="row">
    <!-- begin col-10 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-validation-1">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload" onclick="window.location.reload()"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title"><?php echo $this->escapeHtml($this->tituloTabla) ?></h4>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <form class="form-inline" method="post" action="">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </div>
                                <input type="text" name="email" class="form-control" id="exampleInputAmount" placeholder="Buscar email" autocomplete="off" value="<?php echo (isset($this->email)) ? $this->email : '' ?>">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">buscar</button>
                    </form><br/>
                    
                    <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Position</th>
                                <th>Salary</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->empleados as $key => $empleado): ?>
                            <tr class="">
                                <td><?php echo $empleado->getName() ?></td>
                                <td><?php echo $empleado->getEmail() ?></td>
                                <td><?php echo $empleado->getPosition() ?></td>
                                <td><?php echo $empleado->getSalary() ?></td>
                                <td>
                                    <a onclick="btnModal('<?php echo $this->url('prueba/default', array('controller'=>'prueba', 'action' =>'detalle', 'id' => $empleado->getId()))?>')" href="#" data-toggle="tooltip" data-placement="top" title="Ver detalle"><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> Detalle</a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-10 -->
</div>
<!-- end row -->

<!-- modal-dialog -->
<div class="modal fade" id="modal">
    <div class="modal-dialog">
        <div class="modal-content" id="contenido-modal">
        </div>
    </div>
</div>
<!-- end modal-dialog -->