<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title"><?php echo $this->escapeHtml($this->titulo) ?></h4>
</div>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('sistemas/default', array('controller'=>'area', 'action' =>'registrar')));
echo $this->form()->openTag($form);
?>
    <fieldset>
        <div class="modal-body">
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputNombre">Area</label>
                <div class="col-md-5">
                    <?php
                    $nombre = $form->get('nombre');
                    echo $this->formInput($nombre);
                    echo $this->formElementErrors($nombre);
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputEstado">Estado</label>
                <div class="col-md-5">
                    <?php
                    $estado = $form->get('estado');
                    echo $this->formSelect($estado);
                    echo $this->formElementErrors($estado);
                    ?>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <?php echo $this->formElement($form->get('guardar')) ?>
            <?php echo $this->formElement($form->get('cancelar')) ?>
        </div>
    </fieldset>
<?php echo $this->form()->closeTag() ?>