<!-- begin page-header -->
<h1 class="page-header"><?php echo $this->escapeHtml($this->titulo) ?> <small><?php echo $this->escapeHtml($this->tituloAlterno) ?></small></h1>
<!-- end page-header -->

<!-- begin row -->
<div class="row">
    <!-- begin col-10 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-validation-1">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload" onclick="window.location.reload()"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title"><?php echo $this->escapeHtml($this->tituloTabla) ?></h4>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <div class="form-inline">
                        <button type="button" class="btn btn-sm btn-primary m-r-5" onclick="btnModal('<?php echo $this->url('sistemas/default', array('controller'=>'persona', 'action' =>'registrar'))?>');" data-toggle="tooltip" data-placement="top" title="Registro Nuevo"><i class="fa fa-lg fa-plus"></i></button>
                    </div><br/>
                    
                    <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Persona</th>
                                <th>Correo</th>
                                <th>Area</th>
                                <th>Estado</th>
                                <th>Fecha de Registro</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->listar as $key => $fila): ?>
                            <tr class="">
                                <td><?php echo ++$key ?></td>
                                <td><?php echo $fila->getNombre()." ".$fila->getApellidoPaterno()." ".$fila->getApellidoMaterno() ?></td>
                                <td><?php echo $fila->getCorreo() ?></td>
                                <td><?php echo $fila->getArea() ?></td>
                                <td><?php echo $fila->getEstado() ?></td>
                                <td><?php echo $fila->getFechaRegistro() ?></td>
                                <td>
                                    <a onclick="btnModal('<?php echo $this->url('sistemas/default', array('controller'=>'persona', 'action' =>'modificar', 'id' => $fila->getIdPersona()))?>')" href="#" data-toggle="tooltip" data-placement="top" title="Editar Registro"><i class="fa fa-lg fa-edit"></i></a>
                                    &nbsp;&nbsp;&nbsp;
                                    <a onclick="btnModal('<?php echo $this->url('sistemas/default', array('controller'=>'persona', 'action' =>'eliminar', 'id' => $fila->getIdPersona()))?>')" href="#" data-toggle="tooltip" data-placement="top" title="Eliminar Registro"><i class="fa fa-lg fa-trash-o"></i></a>
                                    &nbsp;&nbsp;&nbsp;
                                    <a onclick="btnModal('<?php echo $this->url('sistemas/default', array('controller'=>'usuario', 'action' =>'registrar', 'id' => $fila->getIdPersona()))?>')" href="#" data-toggle="tooltip" data-placement="top" title="Crear Usuario"><i class="fa fa-lg fa-user"></i></a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-10 -->
</div>
<!-- end row -->

<!-- modal-dialog -->
<div class="modal fade" id="modal">
    <div class="modal-dialog">
        <div class="modal-content" id="contenido-modal">
        </div>
    </div>
</div>
<!-- end modal-dialog -->