<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title"><?php echo $this->escapeHtml($this->titulo) ?></h4>
</div>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('sistemas/default', array('controller'=>'persona', 'action' =>'registrar')));
echo $this->form()->openTag($form);
?>
    <fieldset>
        <div class="modal-body">
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputNombre">Nombres</label>
                <div class="col-md-7">
                    <?php
                    $nombre = $form->get('nombre');
                    echo $this->formInput($nombre);
                    echo $this->formElementErrors($nombre);
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputApellidoPaterno">Apellido Paterno</label>
                <div class="col-md-7">
                    <?php
                    $apellidoPaterno = $form->get('apellidoPaterno');
                    echo $this->formInput($apellidoPaterno);
                    echo $this->formElementErrors($apellidoPaterno);
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputApellidoMaterno">Apellido Materno</label>
                <div class="col-md-7">
                    <?php
                    $apellidoMaterno = $form->get('apellidoMaterno');
                    echo $this->formInput($apellidoMaterno);
                    echo $this->formElementErrors($apellidoMaterno);
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputArea">Area</label>
                <div class="col-md-7">
                    <?php
                    $area = $form->get('idArea');
                    echo $this->formSelect($area);
                    echo $this->formElementErrors($area);
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputCorreo">Correo</label>
                <div class="col-md-7">
                    <?php
                    $correo = $form->get('correo');
                    echo $this->formInput($correo);
                    echo $this->formElementErrors($correo);
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputFoto">Foto</label>
                <div class="col-md-7">
                    <?php
                    $foto = $form->get('foto');
                    echo $this->formFile($foto);
                    echo $this->formElementErrors($foto);
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="inputEstado">Estado</label>
                <div class="col-md-7">
                    <?php
                    $estado = $form->get('estado');
                    echo $this->formSelect($estado);
                    echo $this->formElementErrors($estado);
                    ?>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <?php echo $this->formElement($form->get('guardar')) ?>
            <?php echo $this->formElement($form->get('cancelar')) ?>
        </div>
    </fieldset>
<?php echo $this->form()->closeTag() ?>